# 100 numpy exercises

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [4]:
np.__version__

'1.26.3'

3. Create a null vector of size 10 

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [14]:
# create numpy 2d array
x = np.array([[10, 4, 5], [6, 2, 4]])

print("Memory size of array: ", x.size)

Memory size of array:  6


5. How to get the documentation of the numpy add function from the command line?

6. Create a null vector of size 10 but the fifth value which is 1

In [15]:
x = np.zeros(10)
print(x)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [23]:
v = np.arange(10, 49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Reverse a vector (first element becomes last)

In [36]:
r = np.arange(10)
r
# Reverse a vector (first elements becomes last)
rev = np.flip(r)
print(rev)

[9 8 7 6 5 4 3 2 1 0]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [34]:
m = np.arange(9).reshape(3, 3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [36]:
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix

In [43]:
i = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

12. Create a 3x3x3 array with random values

In [44]:
r = np.random.standard_normal(size=(3, 3, 3))
r

array([[[ 0.03480632, -1.52658245, -0.50626649],
        [-1.20086649, -1.00725771, -1.07943593],
        [ 0.77923783, -0.43601827, -0.60583007]],

       [[-2.49052015,  0.28449704, -1.78637366],
        [-0.81972451, -0.08103206,  0.53772383],
        [-1.85376418,  0.37124924,  0.29428918]],

       [[ 2.23784297,  0.16173006, -0.00279127],
        [-0.36833604, -0.8728375 , -0.7582425 ],
        [ 0.98600293,  1.47447474,  0.28529202]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [46]:
r = np.random.standard_normal(size=(10, 10))
r

array([[-0.68082887, -0.65959163,  1.11974854,  0.94340963, -1.52132631,
         0.98095846, -0.5253825 , -0.44791343,  0.76586311, -1.03331   ],
       [-1.1665021 , -0.52605868,  0.00594009,  0.06583107,  0.52553772,
         1.28697567,  0.9361274 , -0.47631872,  0.09662537,  0.58040589],
       [ 0.84992427, -0.97609735, -1.55760757,  1.50745905,  0.92986075,
        -0.8992681 , -0.65828778, -0.93017646,  0.38919223, -1.10379674],
       [ 0.83527494,  1.26408319,  0.24929023,  0.54474417,  0.77846408,
         0.98609815,  0.41545724,  1.6550607 , -0.85059852, -0.13088403],
       [-0.33690968, -0.50160595,  1.6022008 ,  0.44903201, -1.85744785,
         0.34378015, -0.43923799,  0.26794157,  1.58978766,  0.66366789],
       [ 0.94856709, -0.58498119,  1.01539041, -0.03434489, -0.12692556,
         0.93146714, -0.78181205, -0.40014305,  0.66273241, -0.46609663],
       [ 0.58377756, -1.4674498 ,  0.81195586,  1.58795108, -0.1714557 ,
        -0.83307604, -1.05797929,  0.10476963

In [50]:
r.min()

-2.8011996867417

In [48]:
r.max()

2.087254509361163

14. Create a random vector of size 30 and find the mean value

In [52]:
r2 = np.random.rand(30)
r2

array([0.37971238, 0.87689214, 0.41545325, 0.05868079, 0.87519019,
       0.57676578, 0.26509016, 0.35216367, 0.6127773 , 0.2132253 ,
       0.222344  , 0.55733777, 0.31995911, 0.88925736, 0.06658471,
       0.29635138, 0.40172882, 0.27249287, 0.30058912, 0.40126037,
       0.77033677, 0.89236883, 0.44623113, 0.97232349, 0.23712067,
       0.1888782 , 0.40398398, 0.19675846, 0.44785658, 0.62870848])

In [53]:
r2.mean()

0.4512807695761009

15. Create a 2d array with 1 on the border and 0 inside 

In [61]:
td = np.ones((5, 5))
print("Original arary:")
print(td)
# set the border elemnts
print("1 on the border and 0 inside in the array")
td[1:-1, 1:-1] = 0
print(td)

Original arary:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [38]:
b = np.ones((5,5))
b = np.pad(b, pad_width=1, mode='constant', constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


 17. What is the result of the following expression?

In [63]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [65]:
d = np.diag([1, 2, 3, 4])
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [39]:
p = np.zeros((8,8),dtype=int)
p[1::2,::2] = 1
p[::2,1::2] = 1
print(p)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [40]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function

In [43]:
c = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [44]:
n = np.random.random((5,5))
n = (n - np.mean (n)) / (np.std (n))
print(n)

[[-0.87622732  1.34290255 -1.43880912  0.99428763  0.64306179]
 [ 1.43682252 -0.96069328 -1.32754083  0.92747985 -1.02797353]
 [ 1.17707543 -1.14743126  1.30455821 -1.1862619  -0.88539982]
 [ 0.60234028  0.15458824  0.25938206  0.39228158 -1.11413469]
 [-1.4932681   0.11154021  0.5033712   0.97276213  0.63528617]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [76]:
x = np.random.random ((5, 3))
x

y = np.random.random ((3, 2))
y

z = np.dot(x, y)
z

array([[0.58163435, 0.96305001],
       [0.53885492, 0.59546931],
       [0.53469194, 1.00687082],
       [0.56628221, 0.70441382],
       [0.2723601 , 0.61163205]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [77]:
z = np.arange(10)
z[(3 < z) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

26. What is the output of the following script?

In [78]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? 

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

28. What are the result of the following expressions?

In [82]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7060\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7060\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7060\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

29. How to round away from zero a float array ?

In [45]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

print(np.where(x>0, np.ceil(x), np.floor(x)))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[ 7. 10.  8.  2. -5. -4. 10.  7. -3.  7.]


30. How to find common values between two arrays? 

In [47]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[4 5 6 7 8 9]


31. How to ignore all numpy warnings (not recommended)?

32. Is the following expressions true?

In [87]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7060\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow?

In [88]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today") 
tomorrow = np.datetime64("today") - np.timedelta64(1)

34. How to get all the dates corresponding to the month of July 2016?

In [90]:
z = np.arange("2016-07", "2016-08", dtype="datetime64[D]")
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [93]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods 

In [95]:
z = np.random.uniform(0, 10, 10)
print(z - z%1)
print(z // 1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[9. 9. 0. 2. 3. 5. 7. 9. 2. 9.]
[9. 9. 0. 2. 3. 5. 7. 9. 2. 9.]
[9. 9. 0. 2. 3. 5. 7. 9. 2. 9.]
[9 9 0 2 3 5 7 9 2 9]
[9. 9. 0. 2. 3. 5. 7. 9. 2. 9.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [96]:
x = np.zeros((5, 5))
x+= np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

38. Consider a generator function that generates 10 integers and use it to build an array

In [5]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [6]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it 

In [8]:
v = np.random.random(10)
v.sort()
print(v)


[0.00847659 0.03055292 0.16899918 0.26572799 0.29073611 0.29453039
 0.3677895  0.40522945 0.69127052 0.83246239]


41. How to sum a small array faster than np.sum?

In [9]:
s = np.arange(10)
np.add.reduce(s)

45

42. Consider two random array A and B, check if they are equal

In [10]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)


In [11]:
equal = np.allclose(a,b)
print(equal)


False


In [12]:
equal = np.array_equal(a,b)
print(equal)


False


43. Make an array immutable (read-only) 

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [16]:
c = np.random.random((10,2))
a,b = c[:,0], Z[:,1]
e = np.sqrt(a**2+b**2)
f = np.arctan2(b,a)
print(e)
print(f)

[0.55615145 1.10121719 0.16356196 1.11105934 0.94911163 1.08451181
 0.54832164 0.96357415 0.62874229 0.69934812]
[0.54053457 1.10830338 0.53182384 0.97468025 1.32391847 0.82765826
 0.28175617 0.21342003 1.42774396 1.43901723]


45. Create random vector of size 10 and replace the maximum value by 0

In [17]:
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.49134729 0.         0.83644825 0.70249974 0.83532699 0.29139701
 0.73814425 0.19612188 0.5100432  0.88046616]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [18]:
s = np.zeros((5,5), [('x',float),('y',float)])
s['x'], s['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(s)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [19]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


48. Print the minimum and maximum representable value for each numpy scalar type

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? 

In [101]:
np.set_printoptions(threshold=float("inf"))
v = np.zeros((20, 20))
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

50. How to find the closest value (to a given scalar) in a vector?

In [100]:
s = np.arange(100)
z = np.random.uniform(0, 100)
index = (np.abs(s-z)).argmin()
print(s[index])

48


51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [23]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7608\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [51]:
r = np.random.random((10,2))
x,y = np.atleast_2d(r[:,0], r[:,1])
p = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(p)

[[0.         1.10612036 0.95610884 0.89527891 0.4641807  0.73844046
  0.89866005 0.32304491 0.38026625 0.78772565]
 [1.10612036 0.         0.27130865 0.38838367 0.90322484 0.70215734
  0.45707079 0.86420688 0.76804058 0.36609236]
 [0.95610884 0.27130865 0.         0.11771545 0.870706   0.75896756
  0.18598534 0.67069782 0.58479657 0.16993399]
 [0.89527891 0.38838367 0.11771545 0.         0.86793446 0.79794594
  0.07373449 0.59328083 0.51621216 0.15643766]
 [0.4641807  0.90322484 0.870706   0.86793446 0.         0.3091006
  0.90784791 0.55736911 0.51811625 0.71588906]
 [0.73844046 0.70215734 0.75896756 0.79794594 0.3091006  0.
  0.85695026 0.72128443 0.64604575 0.64364579]
 [0.89866005 0.45707079 0.18598534 0.07373449 0.90784791 0.85695026
  0.         0.5866041  0.5185512  0.21370078]
 [0.32304491 0.86420688 0.67069782 0.59328083 0.55736911 0.72128443
  0.5866041  0.         0.09927646 0.51162677]
 [0.38026625 0.76804058 0.58479657 0.51621216 0.51811625 0.64604575
  0.5185512  0.099276

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [24]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[16 91 83 17 93 65 18  2 44 20]


54. How to read the following file?

In [52]:
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

SyntaxError: invalid syntax (2460604331.py, line 2)

55. What is the equivalent of enumerate for numpy arrays?

In [25]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. Generate a generic 2D Gaussian-like array

In [26]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array? 

In [21]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix 

In [24]:
x = np.random.rand(10, 5)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.24839553 -0.36424281 -0.44911197  0.25282566  0.3121336 ]
 [ 0.05191723 -0.0216332  -0.21417468  0.13737858  0.04651206]
 [ 0.0849606  -0.31680984  0.23411749  0.27751753 -0.27978578]
 [ 0.06941891  0.26659424 -0.03856064 -0.13371896 -0.16373355]
 [ 0.07106696 -0.40113293 -0.3460563   0.25756854  0.41855373]
 [ 0.26042119 -0.03637131 -0.26437867  0.26573018 -0.22540139]
 [ 0.49159457 -0.26452897 -0.08292676 -0.18196967  0.03783083]
 [-0.43042389  0.07390683 -0.1006979   0.36950422  0.08771074]
 [-0.31117627  0.44907902 -0.03184229  0.02287896 -0.12893942]
 [ 0.15856583  0.43511805 -0.16786651 -0.41463608 -0.01118129]]


59. How to sort an array by the nth column?

In [27]:
s = np.random.randint(2,5,(3,6))
print(s)
print(s[s[:,1].argsort()])


[[4 4 3 4 4 4]
 [4 3 2 2 3 3]
 [4 3 3 3 2 3]]
[[4 3 2 2 3 3]
 [4 3 3 3 2 3]
 [4 4 3 4 4 4]]


60. How to tell if a given 2D array has null columns?

In [27]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


61. Find the nearest value from a given value in an array 

In [29]:
Z = np.random.uniform(0,1,20)
z = 0.6
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6168593558649272


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [28]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute

In [29]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [31]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 3. 2. 4. 3. 4. 3. 3. 1. 4.]
[5. 5. 3. 7. 5. 7. 5. 5. 1. 7.]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [31]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [32]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


67. Considering a four dimensions array, how to get sum over the last two axis at once? 

In [34]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[58 50 73 75]
 [36 55 40 48]
 [44 54 69 35]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [35]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())


C:\Users\Z-deen\AppData\Local\Temp\ipykernel_7608\1798176149.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


[0.27002449 0.56506918 0.34175722 0.58956778 0.53739082 0.46484898
 0.56753742 0.40875433 0.39893895 0.5889958 ]
0    0.270024
1    0.565069
2    0.341757
3    0.589568
4    0.537391
5    0.464849
6    0.567537
7    0.408754
8    0.398939
9    0.588996
dtype: float64


69. How to get the diagonal of a dot product? 

In [36]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.28231477, 1.51875553, 0.5630088 , 1.23573669, 0.94946721])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [32]:
v = np.array([1,2,3,4,5])
nx = 3
z0 = np.zeros(len(v) + (len(v)-1)*(nx))
z0[::nx+1] = z
print(z0)

[0.6 0.  0.  0.  0.6 0.  0.  0.  0.6 0.  0.  0.  0.6 0.  0.  0.  0.6]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [33]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array?

In [34]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

75. How to compute averages using a sliding window over an array? 

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

77. How to negate a boolean, or to change the sign of a float inplace? 

In [18]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.93933448,  0.53223999,  0.05128197,  0.14712008, -0.11939519,
        0.41475728,  0.83090837, -0.48150921,  0.02620549, -0.92935334,
        0.03389765,  0.83031385, -0.53626236, -0.22001672,  0.5211578 ,
        0.85360234, -0.41477979, -0.87672231, -0.8817441 , -0.69650109,
       -0.40135367,  0.50012007, -0.90992431,  0.08354439, -0.8775112 ,
        0.68110419,  0.16826025,  0.47837817,  0.10181629, -0.0783608 ,
        0.67500768, -0.84649178,  0.54304371,  0.417098  ,  0.28729833,
        0.44282829,  0.37038637, -0.03677499, -0.1368929 ,  0.14418839,
        0.34488875,  0.03052662, -0.56952764,  0.96539018,  0.5203299 ,
        0.97179032,  0.78361747, -0.56812787, -0.0205111 , -0.1029455 ,
       -0.60598932,  0.54772436, -0.97985309, -0.17457786,  0.03077824,
        0.04619328, -0.2221015 ,  0.92848242,  0.61181013,  0.75296728,
        0.08371824,  0.05280788, -0.85239997, -0.13140166,  0.74393573,
        0.82692706,  0.04274392,  0.73612375, -0.93211547, -0.65

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [19]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.01981     6.42004319  1.91621285  2.07349913 11.4181814   1.22846296
  2.11997757  0.30035675  0.85760225  3.86215741]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [20]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[19.06716426  9.42318254 12.16703397  5.1202204   1.0693374   5.81996248
  12.75764177 11.27958372  3.03792088 15.49421817]
 [17.31502795  6.54757509  5.01321631  4.6455783   6.37472703  3.27069015
   4.76980207 13.05197495  4.03361334  7.13960646]
 [ 0.97094232  8.33481641  0.59475447 13.00775258 12.44760603  2.38983244
   2.29832644  6.03615234 14.68431414  6.42692589]
 [12.27589482  2.69329614  7.0421969   1.61036775  3.62842604  4.03614826
   8.43697187  4.97674594  3.45927125 11.66752222]
 [ 2.05389202  7.60267801  1.5230851  11.55677974  9.74767052  0.09098138
   0.93001619  4.01382992 12.84847566  4.83191432]
 [14.17153309  3.09281393  0.90240056  1.90638192  6.14339062  6.66948882
   0.72069685 11.14781128  1.82286943  3.17180027]
 [17.02476479  6.5178532   6.1143454   4.07225235  4.69852466  1.39316531
   6.1410767  12.01322871  3.15103872  8.64387509]
 [14.03041314  2.37451843  2.1649293   2.40718542  9.35479929 11.08841115
   2.85871253 12.74233877  3.04447039  0.64826884]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [21]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [16]:
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


NameError: name 'sliding_window_view' is not defined

82. Compute a matrix rank

In [13]:
z = np.random.uniform(0,1,(10,10))
u, s, v = np.linalg.svd(z) # Singular Value Decomposition
rank = np.sum(s > 1e-10)
print(rank)

10


83. How to find the most frequent value in an array?

In [35]:
f = np.random.randint(0,10,50)
print(np.bincount(f).argmax())

9


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [10]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(c)

NameError: name 'stride_tricks' is not defined

85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [11]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 10  7 12 15]
 [10  0  5  3  9]
 [ 7  5  7 42 12]
 [12  3 42  3  4]
 [15  9 12  4  9]]


86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [8]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [7]:
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

88. How to implement the Game of Life using numpy arrays?

In [6]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


89. How to get the n largest values of an array 

In [5]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5

print (z[np.argsort(z)[-n:]]) # Slow
print (z[np.argpartition(-z,n)[:n]]) # Fast

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [3]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. How to create a record array from a regular array?

In [21]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [22]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [17]:
A = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

AxisError: axis 3 is out of bounds for array of dimension 3

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [15]:
z = np.random.randint(0,5,(10,3))
print(z)
e = np.all(z[:,1:] == z[:,:-1], axis=1)
u = z[~e]
print(u)
u = z[z.max(axis=1) != z.min(axis=1),:]
print(u)

[[2 4 0]
 [3 2 4]
 [3 4 2]
 [2 4 0]
 [1 1 3]
 [2 1 3]
 [1 4 2]
 [3 3 3]
 [0 4 2]
 [3 2 4]]
[[2 4 0]
 [3 2 4]
 [3 4 2]
 [2 4 0]
 [1 1 3]
 [2 1 3]
 [1 4 2]
 [0 4 2]
 [3 2 4]]
[[2 4 0]
 [3 2 4]
 [3 4 2]
 [2 4 0]
 [1 1 3]
 [2 1 3]
 [1 4 2]
 [0 4 2]
 [3 2 4]]


95. Convert a vector of ints into a matrix binary representation 

In [12]:
c = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
v = ((c.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(v[:,::-1])
b = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(c[:, np.newaxis], axis=1))



[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


TypeError: Expected an input array of unsigned byte data type

96. Given a two dimensional array, how to extract unique rows?

In [10]:
z = np.random.randint(0,2,(6,3))
t = np.ascontiguousarray(z).view(np.dtype((np.void, z.dtype.itemsize * z.shape[1])))
_, idx = np.unique(t, return_index=True)
ur = z[idx]
print(ur)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [9]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)       
np.einsum('i,i->i', a, b) 
np.einsum('i,i', a, b)    
np.einsum('i,j->ij', a, b)    

array([[0.06383322, 0.53930242, 0.080372  , 0.43785404, 0.12126645,
        0.49003183, 0.21968206, 0.01654347, 0.63348834, 0.58044523],
       [0.02561027, 0.21637135, 0.03224573, 0.17566966, 0.04865282,
        0.1966037 , 0.08813775, 0.00663734, 0.25415931, 0.23287809],
       [0.08577503, 0.72468037, 0.10799879, 0.58836048, 0.16295015,
        0.65847368, 0.29519481, 0.02223007, 0.85124144, 0.77996547],
       [0.01156555, 0.09771291, 0.01456211, 0.0793321 , 0.02197153,
        0.08878588, 0.03980285, 0.00299741, 0.11477788, 0.10516733],
       [0.03666624, 0.309779  , 0.04616623, 0.25150636, 0.06965628,
        0.28147764, 0.12618688, 0.00950268, 0.36388004, 0.33341171],
       [0.03923631, 0.33149253, 0.04940218, 0.26913535, 0.07453874,
        0.30120742, 0.13503177, 0.01016876, 0.3893857 , 0.35678174],
       [0.06093032, 0.51477695, 0.07671698, 0.41794206, 0.1157517 ,
        0.467747  , 0.20969173, 0.01579113, 0.60467964, 0.55404873],
       [0.05227154, 0.44162222, 0.0658147

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 

In [8]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
m = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [6]:
x = np.random.randn(100) # random 1D array
n = 1000 # number of bootstrap samples
idx = np.random.randint(0, x.size, (n, x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.32994352  0.04201094]
